require:
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleWithoutDescription:
  EnforcedStyle: single_line_only

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleMemoizedHelpers:
  Max: 10
