name: CI

on:
  push:
    branches:
      - main

  pull_request:

env:
  OPENAI_ACCESS_TOKEN: DUMMY_TOKEN
  RECORD: none

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.0'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      uses: paambaati/codeclimate-action@v5.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: bundle exec rake
        coverageLocations: |
          ${{github.workspace}}/tmp/coverage/coverage.xml:cobertura

  steep:
    runs-on: ubuntu-latest
    name: Steep
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Cache RBS Collection
        uses: actions/cache@v4
        with:
          path: .gem_rbs_collection
          key: ${{ runner.os }}-rbs-collection-${{ hashFiles('rbs_collection.lock.yaml') }}
      - name: Rbs Collection
        run: bundle exec rbs collection install
      - name: Steep
        run: bundle exec steep check
